import JSZip from "jszip";
import { z } from "zod";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const InputSchema = z.object({
  paper: z
    .object({
      title: z.string().optional()
    })
    .optional(),
  understanding: z.object({
    problem: z.string(),
    methodology: z.string(),
    architecture: z.array(z.string()).optional(),
    inputs: z.string(),
    outputs: z.string()
  }),
  implementationPlan: z.object({
    stack: z.object({
      frontend: z.string(),
      backend: z.string(),
      orchestration: z.string().optional(),
      evaluation: z.string().optional()
    }),
    apiEndpoints: z.array(z.object({ method: z.string(), path: z.string(), purpose: z.string() })).default([]),
    folderStructure: z.array(z.string()).default([]),
    dependencies: z.array(z.string()).default([]),
    milestones: z.array(z.string()).default([])
  })
});

function sanitizeName(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 40);
}

function toTreeLines(paths: string[]): string {
  const p = Array.from(new Set(paths.map((x) => x.trim()).filter(Boolean))).sort();
  if (p.length === 0) return "- (not provided)";
  return p.map((x) => `- ${x}`).join("\n");
}

export async function POST(req: Request) {
  try {
    const body = InputSchema.parse(await req.json());
    const title = body.paper?.title?.trim() || "paper2product-starter";
    const slug = sanitizeName(title) || "paper2product-starter";
    const root = `${slug}/`;

    const zip = new JSZip();

    const readme = `# ${title}

Generated by Paper2Product AI.

## Problem
${body.understanding.problem}

## Methodology
${body.understanding.methodology}

## Architecture
${(body.understanding.architecture || []).map((x) => `- ${x}`).join("\n") || "- (not provided)"}

## MVP Plan

### Stack
- Frontend: ${body.implementationPlan.stack.frontend}
- Backend: ${body.implementationPlan.stack.backend}
${body.implementationPlan.stack.orchestration ? `- Orchestration: ${body.implementationPlan.stack.orchestration}\n` : ""}${
      body.implementationPlan.stack.evaluation ? `- Evaluation: ${body.implementationPlan.stack.evaluation}\n` : ""
    }

### API Endpoints
${body.implementationPlan.apiEndpoints.length ? "" : "- (not provided)"}
${body.implementationPlan.apiEndpoints
  .map((e) => `- ${e.method.toUpperCase()} ${e.path}: ${e.purpose}`)
  .join("\n")}

### Folder Structure (from plan)
${toTreeLines(body.implementationPlan.folderStructure)}

### Milestones
${body.implementationPlan.milestones.length ? "" : "- (not provided)"}
${body.implementationPlan.milestones.map((m) => `- ${m}`).join("\n")}

---

## Quickstart (generated scaffold)

### Backend
\`\`\`bash
cd backend
python -m venv .venv
./.venv/Scripts/activate  # Windows PowerShell
pip install -r requirements.txt
python main.py
\`\`\`

### Frontend
\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`
`;

    zip.file(`${root}README.md`, readme);

    // --- backend (FastAPI stub)
    zip.file(
      `${root}backend/requirements.txt`,
      `fastapi>=0.115.0,<1.0.0
uvicorn[standard]>=0.30.0,<1.0.0
`
    );

    zip.file(
      `${root}backend/main.py`,
      `from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="${title} API")

class AnalyzeRequest(BaseModel):
    text: str

@app.get("/health")
def health():
    return {"ok": True}

@app.post("/analyze")
def analyze(req: AnalyzeRequest):
    # TODO: implement the core method from the paper here
    return {
        "summary": "stub",
        "inputs": ${JSON.stringify(body.understanding.inputs)},
        "outputs": ${JSON.stringify(body.understanding.outputs)},
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
`
    );

    // --- frontend (Next.js minimal)
    zip.file(
      `${root}frontend/package.json`,
      JSON.stringify(
        {
          name: `${slug}-frontend`,
          private: true,
          version: "0.1.0",
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: { next: "^14.2.35", react: "^18.3.1", "react-dom": "^18.3.1" }
        },
        null,
        2
      )
    );
    zip.file(
      `${root}frontend/next.config.mjs`,
      `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`
    );
    zip.file(
      `${root}frontend/tsconfig.json`,
      JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            lib: ["dom", "dom.iterable", "esnext"],
            strict: true,
            noEmit: true,
            module: "esnext",
            moduleResolution: "bundler",
            jsx: "preserve"
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
          exclude: ["node_modules"]
        },
        null,
        2
      )
    );
    zip.file(`${root}frontend/next-env.d.ts`, `/// <reference types="next" />\n`);
    zip.file(
      `${root}frontend/app/page.tsx`,
      `"use client";

import { useState } from "react";

export default function Page() {
  const [text, setText] = useState("");
  const [out, setOut] = useState<any>(null);
  const [busy, setBusy] = useState(false);

  async function run() {
    setBusy(true);
    setOut(null);
    const res = await fetch("http://127.0.0.1:8000/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text })
    });
    setOut(await res.json());
    setBusy(false);
  }

  return (
    <main style={{ padding: 24, fontFamily: "system-ui" }}>
      <h1>${title}</h1>
      <p><b>Goal:</b> ${body.understanding.problem}</p>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Paste input..."
        style={{ width: "100%", height: 140 }}
      />
      <div style={{ marginTop: 12 }}>
        <button onClick={run} disabled={busy || !text.trim()}>
          {busy ? "Running..." : "Run"}
        </button>
      </div>
      {out ? (
        <pre style={{ marginTop: 12, background: "#111", color: "#eee", padding: 12, overflow: "auto" }}>
          {JSON.stringify(out, null, 2)}
        </pre>
      ) : null}
    </main>
  );
}
`
    );

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });

    return new Response(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${slug}.zip"`
      }
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : "Unknown error";
    return Response.json({ ok: false, error: message }, { status: 400 });
  }
}


